### ISSUE TITLE
beta.openai.com/playground support possible ?

### ISSUE THREAD

**Issue by LiamC-AI** [taishi55/chatgpt-phantom#3]
This is not an issue but more a suggestion. This is working nicely but as a free user of ChatGPT i get too much of these "can't finish the answer" ,"there was an error generating a response" messages while using this. Probably the length of the prompts generated and the length of the answer required, and of course .. ChatGPT load and new sub options ..

Do you think your extension could include/work with OpenAi playground ? (aka beta.openai.com/playground ) ?
I usually use it when GPT is overloaded and doesn't answer. text-davinci-003 is decently good as well and moreover, uptime is mostly 100% from my tests so that would be interesting to try it there.

**Comment by taishi55** [comment]
@LiamC-AI 
> Probably the length of the prompts generated and the length of the answer required,

Yes, if the generated prompt is too large, my free server will be out of memory and cause the error. 
I will try to filter large texts and minimize the capacity of memory for each request. 


> Do you think your extension could include/work with OpenAi playground ?

If you try to input the same query text (Info and Instructions) into the playground, you will notice how powerful ChatGPT is compared to text-davinci-003. 

text-davinci-003 is capable to generate some texts based on a short and concise prompt. However, it is not capable to understand a prompt including large strings. Phantom feeds real-time data with the prompt. text-davinci-003 is not capable enough to handle the prompt based on a large text.

**Comment by X13X** [comment]
Queuing and load balancing would be ideal.  

Calculate the total memory -> (pop queue) => incoming message size -> [ make space ] -> send to user (while) looping back to (pop queue).

Taishi55 I think your good enough to pull something like that off.

**Comment by taishi55** [comment]
@X13X I'm looking for a way to calculate the memory of strings before it is passed into a variable. Once a large text is passed into a variable, the request will be crushed and returns an error.

**Comment by taishi55** [comment]
@LiamC-AI Could tell me your prompt that often returns errors. It would be helpful for me to investigate in detail.

**Comment by LiamC-AI** [comment]
I deleted most of them unfortunately, but that was mostly even simple requests with no custom prompts (using your default 4 paragraph news article). But then it usually throw an error, but works the next try (then i eventually gets ChatGPT stalling during its answer but that's another thing).

like this simple one : https://postimg.cc/hzx3CP02

i remember it got a bit temperamental (like 3 errors in a row) with a question related to some videogame news but i deleted related history sorry. Nothing terrible really , it just made me wonder if i was doing something wrong.

**Comment by taishi55** [comment]
@LiamC-AI Currently I'm not experiencing any error with the prompt. When you were using the prompt, I think one of the real-time data sources wasn't readable for the server.
