### ISSUE TITLE
For french ...

### ISSUE THREAD

**Issue by alexruben007** [taishi55/chatgpt-phantom#4]
Hello. I'm using your app which is realy Huge ! Is it possible on your side to had french (France) to the countries sources ? 
Best regards.

**Comment by alexruben007** [comment]
I can see that Phantom is scraping results without special characters :
ç – the cedilla (la cédille)
é – the acute accent (l'accent aigu)
â/ê/î/ô/û – the circumflex (l'accent circonflexe)
à/è/ì/ò/ù – the grave accent (l'accent grave)
ë/ï/ü – the trema (l'accent tréma)

So if you add french maybe there is something to do on this side ;)

**Comment by taishi55** [comment]
@alexruben007 currently supporting English only, so all other languages including special letters are removed. 
In the near future, I will definitely make it available to generate all languages too!

**Comment by taishi55** [comment]
@alexruben007 Now French is available! Check it out the new version. 

https://chatgpt-phantom.vercel.app/

**Comment by alexruben007** [comment]
Cool. Thx
