### ISSUE TITLE
[Feature request] Saving custom instructions

### ISSUE THREAD

**Issue by infinitnet** [taishi55/chatgpt-phantom#5]
It would be amazing if we could save custom instructions as templates we can then select from the dropdown. :)

**Comment by taishi55** [comment]
@infinitnet Yes I will definitely do that. For the next update, I will add the following features. 

1. automatically save your custom instruction
2. a button that lets you export the conversation in PDF
3. a button that lets you copy the article in HTML
4. a button that read the text aloud
5. a button that lets you input texts by your voice. 
6. word counts
7. crawl more trustful sources
8. write articles based on sources for prompts (Currently, the prompt portion is missing.)

PS: I fixed a current design issue with the change in ChatGPT. It will take a few days for Chrome to recognize my changes.

**Comment by infinitnet** [comment]
@taishi55 That's a lot of new features for a single update! Very promising. If you keep up that pace, you should get close to AIPRM pretty soon -- depending on which direction you see this extension going of course.

**Comment by taishi55** [comment]
@infinitnet Hey successfully updated the features!! Now you can save your custom instructions and more. Update your version and try it out.

https://chatgpt-phantom.vercel.app/
